version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres:14.1
    ports:
      - "5432:5432"
    volumes: 
      - postgres-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: abcd1234
      POSTGRES_DB: docker
    networks:
      - default
      - postgres
  postgresadmin:
    container_name: postgresadmin
    image: dpage/pgadmin4:4.18
    environment:
      PGADMIN_DEFAULT_EMAIL: docker@gmail.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - postgresadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - default
      - postgresadmin

volumes:
    postgres-db:
    postgresadmin-data:

networks:
  postgres:
    name: postgres
  postgresadmin:
    name: postgresadmin